version: '2'
services:
  passbolt:
    restart: unless-stopped
    build: .
    image: passbolt_debian
    ports: 
      - "8081:8081"
      - "80:80"
      - "443:443"
    networks:
      passbolt-net:
        aliases:
          - passbolt.docker
    env_file:
      - conf/conf.sh
    volumes:
      - ${PASSBOLT_DIR}:/var/www/passbolt


networks:
  passbolt-net:
    driver: bridge 

